timeout: '1200s'  # 10min

steps:
  # maven:3-eclipse-temurin-21. Pin sha for reproducible builds
  - name: maven@sha256:e895a7e85a1acb128d3670fa3ee45f2a9f07836b28364d19a4ab2916f9dd2e14abc
    id: Maven_Build_Service
    args: ['mvn', 'clean', 'install', '-B', '-X']
  - name: gcr.io/cloud-builders/docker
    id: Build_Docker_Image
    # entrypoint: bash
    # # args:
    # #   - -c
    # #   - |
    # #     docker build -t us-central1-docker.pkg.dev/chizhg-louhi-test/gcb-dev/cat-service-gcb-bcid-l2:latest .
dependencies:
- gitSource:
    repository:
      url: "https://cloud-release-internal.googlesource.com/cat-service"
    revision: "46e3b02f0d017914a06b90d4881d2a69e2f4c139"
    destPath: "source"
images:
  ['us-central1-docker.pkg.dev/chizhg-louhi-test/gcb-dev/cat-service-gcb-bcid-l2:latest']
