
steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    echo "FROM ubuntu" > Dockerfile1
    echo "RUN apt-get update" >> Dockerfile1
    echo "ENTRYPOINT ['echo', '$BUILD_ID']" >> Dockerfile1
    docker build -t us-central1-docker.pkg.dev/emilyyfchen-test/wf-test/hello -f Dockerfile1 .
images: ['us-central1-docker.pkg.dev/emilyyfchen-test/wf-test/hello']
dependencies:
- git_source:
    repository:
      url: "https://github.com/ronanww/node-amqp.git"
    revision: "master"
    dest_path: "node-amqp"
    recurse_submodules: true
- git_source:
    repository:
      url: "https://github.com/ronanww/cloud-builders.git"
    revision: "7a4a9af10a6acbc2c6c6f40522eb38e199f8c28d"
    dest_path: "cloud-builders"
    depth: 5
